defaults:
  - model: unet2d
  - vae: sd_vae_ft_mse
  - data: celeba_256
  - optim: adamw
  - loss: eps_linear
  - logging: default
  - checkpoints: default

train:
  resume: "~/Projects/alchemy/src/alchemy/lab/output/weights/faces_1/unet_step00130000.pt"
  precision: fp32
  max_steps: 50000
  lr: 0.0002
  ema_decay: 0.9999
  log_dir: "~/Projects/alchemy/src/alchemy/lab/output/tensorboard/1"
  experiment_name: "default"
  save_every_n_steps: 5000
  save_path: "~/Projects/alchemy/src/alchemy/lab/output/weights/faces_1"
  save_prefix: "unet"

dist:
  backend: nccl